version: "3.9"

services:
  sparsh-ui:
    container_name: sparsh-ui
    image: sparsh-ui:latest
    build:
      context: ui
    ports:
      - 3000:3000
    # depends_on:
      # - sparsh-api
    command: npx pm2-runtime npm -- start --watch
    environment:
      NODE_ENV: production
    volumes:
      - staticbuild:/app/public
    networks:
      sparsh-network:
        aliases:
          - sparsh-ui

  infra:
    container_name: ui-infra
    image: ui-infra:latest
    build:
      context: infra
    networks:
      sparsh-network:
        aliases:
          - ui-infra

volumes:
  staticbuild:

networks:
  sparsh-network:
    name: sparsh-network
    driver: bridge