version: "3.9"

services:
  sparsh-ui:
    container_name: sparsh-ui
    build:
      context: ./ui
    # depends_on:
      # - sparsh-api
    command: npx pm2-runtime npm -- start --watch
    environment:
      NODE_ENV: production
    volumes:
      - staticbuild:/app/public
    networks:
      sparsh-network:
        aliases:
          - sparsh-ui
  
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - staticbuild:/app/public
    depends_on:
      - sparsh-ui
      # - sparsh-app
    networks:
      sparsh-network:
        aliases:
          - nginx

  infra:
    container_name: infra
    build:
      context: infra
    networks:
      sparsh-network:
        aliases:
          - ui-infra

volumes:
  staticbuild:

networks:
  sparsh-network:
    name: sparsh-network
    driver: bridge