version: "3.9"

services:
  ui:
    container_name: ui
    build:
      context: src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      dev:

  infra:
    container_name: infra
    build:
      context: infra
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules

networks:
  dev:
