version: "3.9"

services:
  sparsh-ui:
    container_name: sparsh-ui
    build:
      context: ./ui
    command: npm start
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      sparsh-network:
        aliases:
          - sparsh-ui

  infra:
    container_name: infra
    build:
      context: infra
    networks:
      sparsh-network:
        aliases:
          - ui-infra

networks:
  sparsh-network:
    name: sparsh-network
    driver: bridge