version: "3.9"

services:
  sparsh-ui:
    container_name: sparsh-ui
    build:
      context: ui
    environment:
      NODE_ENV: prod
      COMPOSE_PROJECT_NAME: sparsh
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      sparsh-network:
        aliases:
          - sparsh-ui

  infra:
    container_name: infra
    build:
      context: infra
    ports:
      - "3001:3001"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      sparsh-network:
        aliases:
          - ui-infra

networks:
  sparsh-network:
