import Head from 'next/head'
import Header from "../components/Header/Header";


function Home() {
  return (
    <>
      <Head>
        <title>Welcome to SparshApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Glad to have you here at SparshApp</p>
          <Header />
        </div>
      </main>
    </>
  )
}

export default Home;